{
 "title": "FlightAware",
 "description": "For the flight aware demo\n",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "AircraftType",
    "query": "SELECT DISTINCT aircraft_type FROM flight"
   },
   { "name": "String" }
  ]
 },
 "panels": [
  {
   "title": "Planes in the area",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"latitude\", \"longitude\", \"altitude\", \"ident\", \"origin_name\", \"destination_name\" FROM \"flight\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo GROUP BY \"latitude\", \"longitude\", \"altitude\", \"ident\", \"origin_name\", \"destination_name\" "
    }
   ]
  },
  {
   "title": "Aircraft Types",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 14, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT DISTINCT aircraft_type\nFROM flight"
    }
   ]
  },
  {
   "title": "Destination Cities",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"destination_city\" FROM \"flight\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo GROUP BY \"destination_city\" "
    }
   ]
  },
  {
   "title": "Origin Cities",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 20, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"origin_city\" FROM \"flight\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo GROUP BY \"origin_city\" "
    }
   ]
  },
  {
   "title": "Average Altitude",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT AVG(\"altitude\") FROM \"flight\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Flights in the air",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"ident\" FROM \"flight\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo GROUP BY \"ident\" "
    }
   ]
  },
  {
   "title": "Average Ground Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT AVG(\"groundspeed\") FROM \"flight\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Airline Ground Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 11 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"groundspeed\", \"time\", \"ident\" FROM \"flight\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Major Airlines",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT COUNT(DISTINCT ident) AS AmericanAirlines\nFROM flight\nWHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo \nAND ident LIKE '%AAL%';"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT COUNT(DISTINCT ident) AS United\nFROM flight\nWHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo \nAND ident LIKE '%UAL%';"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT COUNT(DISTINCT ident) AS Delta\nFROM flight\nWHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo \nAND ident LIKE '%DAL%';"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT COUNT(DISTINCT ident) AS Southwest\nFROM flight\nWHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo \nAND ident LIKE '%SWA%';"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT COUNT(DISTINCT ident) AS Frontier\nFROM flight\nWHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo \nAND ident LIKE '%FFT%';"
    }
   ]
  },
  {
   "title": "Current Flights Altitudes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 14, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  time,\n  altitude,\n  ident\nFROM flight\nWHERE\n  \"time\" >= $__timeFrom() AND \"time\" <= $__timeTo()\n"
    }
   ]
  },
  {
   "title": "Origin Cities For Specific Aircraft Type",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"origin_city\" FROM \"flight\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND aircraft_type='$AircraftType' GROUP BY \"origin_city\" "
    }
   ]
  },
  {
   "title": "Search Flights VIA Ident String",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"origin_city\",\"destination_city\" FROM \"flight\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND ident='$String' GROUP BY \"origin_city\", \"destination_city\" "
    }
   ]
  }
 ]
}